version: 1.0

stages:
  - name: Set Up Environment
    run: |
      echo "Installing dependencies..."
      apt-get update
      apt-get install -y curl unzip
      curl -sL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs awscli

  - name: Install Node Packages (optional)
    run: |
      if [ -f package.json ]; then
        echo "Installing Node dependencies..."
        npm install
      else
        echo "No package.json found. Skipping npm install."
      fi

  - name: Build Static Website (optional)
    run: |
      if [ -f package.json ]; then
        echo "Running build script..."
        npm run build
      else
        echo "No build step defined. Skipping."
      fi

  - name: Deploy to S3
    env:
      AWS_ACCESS_KEY_ID: AWAKIART44JMPD4H6XFFGY
      AWS_SECRET_ACCESS_KEY: 0C2G5or9aSODtk0Qrr4UAltM8rwgGG0F1FXBR/zQ
      AWS_REGION: ap-south-1
    run: |
      echo "Deploying static site to S3..."
      # Change 'dist' to 'public' or your actual output directory
      aws s3 sync ./dist s3://your-bucket-name --delete
