version: 0.1

stages:
  - name: Install Node.js
    run: |
      echo "Installing Node.js..."
      apt-get update
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs

  - name: Install Dependencies
    run: |
      if [ -f package.json ]; then
        echo "Installing npm packages..."
        npm install
      else
        echo "No package.json found. Skipping."
      fi

  - name: Build Static Website
    run: |
      if [ -f package.json ]; then
        echo "Running build script..."
        npm run build
      else
        echo "No build script found. Skipping."
      fi

  - name: Deploy to S3
    env:
      AWS_ACCESS_KEY_ID: AKIART44JMPD4CLGBF7K
      AWS_REGION: ap-south-1
    run: |
      echo "Deploying to S3..."
      # Change 'dist' to your output folder from the build step
      aws s3 sync ./dist s3://codelearnpipeline --delete --acl public-read

