version: 1.0

stages:
  - name: Install Node.js
    run: |
      echo "Installing Node.js..."
      apt-get update
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs

  - name: Install Dependencies
    run: |
      if [ -f package.json ]; then
        echo "Installing npm packages..."
        npm install
      else
        echo "No package.json found. Skipping."
      fi

  - name: Build Static Website
    run: |
      if [ -f package.json ]; then
        echo "Running build script..."
        npm run build
      else
        echo "No build script found. Skipping."
      fi
